// Mock data for CMMS application

export const workOrders = [
  {
    id: 'WO-001',
    title: 'Replace HVAC Filter - Building A',
    description: 'Monthly filter replacement for main HVAC unit',
    assetId: 'ASSET-001',
    assetName: 'HVAC Unit A1',
    priority: 'high',
    status: 'open',
    assignedTo: 'John Smith',
    assignedToId: 'USER-001',
    createdBy: 'Sarah Johnson',
    createdDate: '2025-01-15T09:00:00Z',
    dueDate: '2025-01-20T17:00:00Z',
    estimatedTime: 2,
    actualTime: null,
    location: 'Building A - Floor 3',
    cost: 150,
    partsUsed: ['Filter-24x24'],
    notes: 'Check for any unusual wear',
    type: 'preventive'
  },
  {
    id: 'WO-002',
    title: 'Emergency Pump Repair',
    description: 'Water pump making unusual noise, potential bearing failure',
    assetId: 'ASSET-005',
    assetName: 'Water Pump P-101',
    priority: 'critical',
    status: 'in-progress',
    assignedTo: 'Mike Chen',
    assignedToId: 'USER-002',
    createdBy: 'Admin',
    createdDate: '2025-01-18T14:30:00Z',
    dueDate: '2025-01-18T23:59:00Z',
    estimatedTime: 4,
    actualTime: 2.5,
    location: 'Building B - Basement',
    cost: 850,
    partsUsed: ['Bearing-2205', 'Seal-Kit-A'],
    notes: 'Ordered replacement bearings',
    type: 'corrective'
  },
  {
    id: 'WO-003',
    title: 'Conveyor Belt Inspection',
    description: 'Quarterly safety inspection of main conveyor system',
    assetId: 'ASSET-012',
    assetName: 'Conveyor Belt CB-1',
    priority: 'medium',
    status: 'completed',
    assignedTo: 'John Smith',
    assignedToId: 'USER-001',
    createdBy: 'System Auto',
    createdDate: '2025-01-10T08:00:00Z',
    dueDate: '2025-01-15T17:00:00Z',
    completedDate: '2025-01-14T15:30:00Z',
    estimatedTime: 3,
    actualTime: 2.8,
    location: 'Warehouse - Section C',
    cost: 200,
    partsUsed: [],
    notes: 'All components in good condition',
    type: 'preventive'
  },
  {
    id: 'WO-004',
    title: 'Lighting Fixture Replacement',
    description: 'Replace 12 LED fixtures in cafeteria',
    assetId: 'ASSET-020',
    assetName: 'Cafeteria Lighting',
    priority: 'low',
    status: 'open',
    assignedTo: 'Tom Wilson',
    assignedToId: 'USER-003',
    createdBy: 'Facilities Manager',
    createdDate: '2025-01-16T10:00:00Z',
    dueDate: '2025-01-25T17:00:00Z',
    estimatedTime: 4,
    actualTime: null,
    location: 'Building A - Cafeteria',
    cost: 600,
    partsUsed: [],
    notes: 'LED-48W fixtures ordered',
    type: 'corrective'
  },
  {
    id: 'WO-005',
    title: 'Compressor Oil Change',
    description: 'Routine oil change for air compressor',
    assetId: 'ASSET-008',
    assetName: 'Air Compressor AC-2',
    priority: 'medium',
    status: 'scheduled',
    assignedTo: 'Mike Chen',
    assignedToId: 'USER-002',
    createdBy: 'System Auto',
    createdDate: '2025-01-17T07:00:00Z',
    dueDate: '2025-01-22T12:00:00Z',
    estimatedTime: 1.5,
    actualTime: null,
    location: 'Building C - Mechanical Room',
    cost: 120,
    partsUsed: ['Compressor-Oil-5L'],
    notes: 'Use synthetic oil',
    type: 'preventive'
  }
];

export const assets = [
  {
    id: 'ASSET-001',
    name: 'HVAC Unit A1',
    category: 'HVAC',
    manufacturer: 'Carrier',
    model: 'AquaEdge 19DV',
    serialNumber: 'HV-2020-1234',
    purchaseDate: '2020-03-15',
    installDate: '2020-04-01',
    warrantyExpiry: '2025-04-01',
    location: 'Building A - Floor 3',
    status: 'operational',
    condition: 'good',
    maintenanceCost: 3200,
    downtime: 12,
    lastMaintenance: '2024-12-15',
    nextMaintenance: '2025-01-20',
    criticality: 'high',
    specifications: { capacity: '50 tons', power: '208V 3-Phase' }
  },
  {
    id: 'ASSET-005',
    name: 'Water Pump P-101',
    category: 'Pumps',
    manufacturer: 'Grundfos',
    model: 'CR 64-1',
    serialNumber: 'WP-2019-5678',
    purchaseDate: '2019-06-20',
    installDate: '2019-07-05',
    warrantyExpiry: '2024-07-05',
    location: 'Building B - Basement',
    status: 'maintenance',
    condition: 'fair',
    maintenanceCost: 1850,
    downtime: 48,
    lastMaintenance: '2024-11-10',
    nextMaintenance: '2025-02-10',
    criticality: 'critical',
    specifications: { flow: '100 GPM', head: '200 ft' }
  },
  {
    id: 'ASSET-012',
    name: 'Conveyor Belt CB-1',
    category: 'Material Handling',
    manufacturer: 'Dorner',
    model: '2200 Series',
    serialNumber: 'CB-2021-9012',
    purchaseDate: '2021-02-10',
    installDate: '2021-03-15',
    warrantyExpiry: '2026-03-15',
    location: 'Warehouse - Section C',
    status: 'operational',
    condition: 'excellent',
    maintenanceCost: 950,
    downtime: 6,
    lastMaintenance: '2025-01-14',
    nextMaintenance: '2025-04-14',
    criticality: 'medium',
    specifications: { length: '50 ft', speed: '100 fpm' }
  },
  {
    id: 'ASSET-008',
    name: 'Air Compressor AC-2',
    category: 'Compressed Air',
    manufacturer: 'Atlas Copco',
    model: 'GA 37',
    serialNumber: 'AC-2018-3456',
    purchaseDate: '2018-09-01',
    installDate: '2018-10-15',
    warrantyExpiry: '2023-10-15',
    location: 'Building C - Mechanical Room',
    status: 'operational',
    condition: 'good',
    maintenanceCost: 2100,
    downtime: 18,
    lastMaintenance: '2024-10-22',
    nextMaintenance: '2025-01-22',
    criticality: 'high',
    specifications: { capacity: '37 kW', pressure: '125 PSI' }
  },
  {
    id: 'ASSET-020',
    name: 'Cafeteria Lighting',
    category: 'Electrical',
    manufacturer: 'Philips',
    model: 'LED Panel 600x600',
    serialNumber: 'LT-2022-7890',
    purchaseDate: '2022-05-10',
    installDate: '2022-06-01',
    warrantyExpiry: '2027-06-01',
    location: 'Building A - Cafeteria',
    status: 'degraded',
    condition: 'fair',
    maintenanceCost: 450,
    downtime: 0,
    lastMaintenance: '2024-06-01',
    nextMaintenance: '2025-06-01',
    criticality: 'low',
    specifications: { wattage: '48W', lumens: '4800 lm' }
  }
];

export const inventory = [
  {
    id: 'INV-001',
    partNumber: 'Filter-24x24',
    name: 'HVAC Air Filter 24x24x2',
    category: 'Filters',
    description: 'MERV 11 pleated air filter',
    quantity: 24,
    minStock: 12,
    maxStock: 48,
    unit: 'pieces',
    unitCost: 15.50,
    location: 'Warehouse - A12',
    supplier: 'FilterCo Inc',
    lastOrdered: '2024-12-01',
    status: 'in-stock'
  },
  {
    id: 'INV-002',
    partNumber: 'Bearing-2205',
    name: 'Ball Bearing 2205-2RS',
    category: 'Bearings',
    description: 'Self-aligning ball bearing with rubber seals',
    quantity: 8,
    minStock: 10,
    maxStock: 30,
    unit: 'pieces',
    unitCost: 45.00,
    location: 'Warehouse - B05',
    supplier: 'Industrial Supply Co',
    lastOrdered: '2025-01-18',
    status: 'low-stock'
  },
  {
    id: 'INV-003',
    partNumber: 'Seal-Kit-A',
    name: 'Pump Seal Repair Kit',
    category: 'Seals',
    description: 'Complete seal kit for water pumps',
    quantity: 15,
    minStock: 8,
    maxStock: 24,
    unit: 'kits',
    unitCost: 78.00,
    location: 'Warehouse - B08',
    supplier: 'Pump Parts LLC',
    lastOrdered: '2024-11-20',
    status: 'in-stock'
  },
  {
    id: 'INV-004',
    partNumber: 'Compressor-Oil-5L',
    name: 'Synthetic Compressor Oil 5L',
    category: 'Lubricants',
    description: 'Full synthetic compressor oil',
    quantity: 32,
    minStock: 20,
    maxStock: 60,
    unit: 'liters',
    unitCost: 25.00,
    location: 'Warehouse - C15',
    supplier: 'Lubes & Oils Direct',
    lastOrdered: '2024-12-10',
    status: 'in-stock'
  },
  {
    id: 'INV-005',
    partNumber: 'LED-48W',
    name: 'LED Panel Light 48W',
    category: 'Lighting',
    description: '600x600 LED panel, 4800 lumens',
    quantity: 3,
    minStock: 12,
    maxStock: 36,
    unit: 'pieces',
    unitCost: 42.00,
    location: 'Warehouse - D20',
    supplier: 'Lighting Solutions Inc',
    lastOrdered: '2025-01-16',
    status: 'critical'
  }
];

export const preventiveMaintenance = [
  {
    id: 'PM-001',
    name: 'HVAC Filter Replacement',
    assetId: 'ASSET-001',
    assetName: 'HVAC Unit A1',
    frequency: 'monthly',
    lastCompleted: '2024-12-15',
    nextDue: '2025-01-20',
    estimatedDuration: 2,
    assignedTo: 'John Smith',
    priority: 'high',
    tasks: ['Remove old filter', 'Inspect housing', 'Install new filter', 'Test airflow'],
    partsRequired: ['Filter-24x24'],
    active: true
  },
  {
    id: 'PM-002',
    name: 'Pump Bearing Inspection',
    assetId: 'ASSET-005',
    assetName: 'Water Pump P-101',
    frequency: 'quarterly',
    lastCompleted: '2024-11-10',
    nextDue: '2025-02-10',
    estimatedDuration: 3,
    assignedTo: 'Mike Chen',
    priority: 'critical',
    tasks: ['Listen for unusual sounds', 'Check vibration levels', 'Inspect seals', 'Lubricate bearings'],
    partsRequired: ['Grease-MultiPurpose'],
    active: true
  },
  {
    id: 'PM-003',
    name: 'Conveyor Safety Inspection',
    assetId: 'ASSET-012',
    assetName: 'Conveyor Belt CB-1',
    frequency: 'quarterly',
    lastCompleted: '2025-01-14',
    nextDue: '2025-04-14',
    estimatedDuration: 3,
    assignedTo: 'John Smith',
    priority: 'medium',
    tasks: ['Inspect belt condition', 'Check alignment', 'Test emergency stop', 'Verify guards'],
    partsRequired: [],
    active: true
  },
  {
    id: 'PM-004',
    name: 'Compressor Oil Change',
    assetId: 'ASSET-008',
    assetName: 'Air Compressor AC-2',
    frequency: 'quarterly',
    lastCompleted: '2024-10-22',
    nextDue: '2025-01-22',
    estimatedDuration: 1.5,
    assignedTo: 'Mike Chen',
    priority: 'medium',
    tasks: ['Drain old oil', 'Replace oil filter', 'Add new synthetic oil', 'Check oil level'],
    partsRequired: ['Compressor-Oil-5L', 'Oil-Filter-C37'],
    active: true
  }
];

export const serviceRequests = [
  {
    id: 'SR-001',
    title: 'AC not cooling properly in Conference Room B',
    description: 'Temperature stays at 78°F even when set to 68°F',
    requestedBy: 'Emily Davis',
    department: 'Sales',
    location: 'Building A - Floor 2 - Conference Room B',
    priority: 'medium',
    status: 'open',
    createdDate: '2025-01-18T11:30:00Z',
    category: 'HVAC',
    relatedAsset: 'ASSET-002'
  },
  {
    id: 'SR-002',
    title: 'Leaking faucet in restroom',
    description: 'Constant drip from sink faucet',
    requestedBy: 'Robert Martinez',
    department: 'Engineering',
    location: 'Building B - Floor 1 - Men\'s Restroom',
    priority: 'low',
    status: 'assigned',
    createdDate: '2025-01-17T09:15:00Z',
    assignedTo: 'Tom Wilson',
    category: 'Plumbing',
    relatedAsset: null
  },
  {
    id: 'SR-003',
    title: 'Forklift making strange noise',
    description: 'Hydraulic system making grinding sound when lifting',
    requestedBy: 'James Anderson',
    department: 'Warehouse',
    location: 'Warehouse - Loading Dock',
    priority: 'high',
    status: 'converted',
    createdDate: '2025-01-16T14:45:00Z',
    convertedToWO: 'WO-006',
    category: 'Equipment',
    relatedAsset: 'ASSET-015'
  }
];

export const locations = [
  {
    id: 'LOC-001',
    name: 'Building A',
    type: 'building',
    address: '123 Industrial Parkway',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62701',
    coordinates: { lat: 39.7817, lng: -89.6501 },
    size: 50000,
    floors: 4,
    assetCount: 42,
    activeWOs: 8
  },
  {
    id: 'LOC-002',
    name: 'Building B',
    type: 'building',
    address: '125 Industrial Parkway',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62701',
    coordinates: { lat: 39.7820, lng: -89.6498 },
    size: 35000,
    floors: 2,
    assetCount: 28,
    activeWOs: 5
  },
  {
    id: 'LOC-003',
    name: 'Warehouse',
    type: 'warehouse',
    address: '130 Industrial Parkway',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62701',
    coordinates: { lat: 39.7825, lng: -89.6495 },
    size: 75000,
    floors: 1,
    assetCount: 65,
    activeWOs: 3
  }
];

export const users = [
  {
    id: 'USER-001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    role: 'Technician',
    department: 'Maintenance',
    phone: '(555) 123-4567',
    activeWOs: 3,
    completedWOs: 145,
    avatar: null
  },
  {
    id: 'USER-002',
    name: 'Mike Chen',
    email: 'mike.chen@company.com',
    role: 'Senior Technician',
    department: 'Maintenance',
    phone: '(555) 234-5678',
    activeWOs: 2,
    completedWOs: 238,
    avatar: null
  },
  {
    id: 'USER-003',
    name: 'Tom Wilson',
    email: 'tom.wilson@company.com',
    role: 'Technician',
    department: 'Facilities',
    phone: '(555) 345-6789',
    activeWOs: 1,
    completedWOs: 89,
    avatar: null
  },
  {
    id: 'USER-004',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Maintenance Manager',
    department: 'Maintenance',
    phone: '(555) 456-7890',
    activeWOs: 0,
    completedWOs: 12,
    avatar: null
  }
];

export const documents = [
  {
    id: 'DOC-001',
    name: 'HVAC Unit A1 Service Manual',
    description: 'Complete service and maintenance manual for Carrier AquaEdge 19DV HVAC system',
    category: 'Preventive Maintenance',
    fileType: 'pdf',
    fileSize: 5242880,
    relatedTo: 'ASSET-001',
    relatedType: 'asset',
    uploadedBy: 'Sarah Johnson',
    uploadedDate: '2020-04-01T10:00:00Z',
    expiryDate: null,
    tags: ['hvac', 'manual', 'carrier']
  },
  {
    id: 'DOC-002',
    name: 'Water Pump Installation Certificate',
    description: 'Installation and commissioning certificate for Water Pump P-101',
    category: 'License & Certification',
    fileType: 'pdf',
    fileSize: 1048576,
    relatedTo: 'ASSET-005',
    relatedType: 'asset',
    uploadedBy: 'Mike Chen',
    uploadedDate: '2019-07-05T14:30:00Z',
    expiryDate: '2024-07-05T23:59:59Z',
    tags: ['certificate', 'pump', 'installation']
  },
  {
    id: 'DOC-003',
    name: 'Safety Inspection Report - Q4 2024',
    description: 'Quarterly safety inspection report for all equipment',
    category: 'Stack Commission',
    fileType: 'pdf',
    fileSize: 2097152,
    relatedTo: null,
    relatedType: null,
    uploadedBy: 'Sarah Johnson',
    uploadedDate: '2024-12-28T16:00:00Z',
    expiryDate: null,
    tags: ['safety', 'inspection', 'report', 'quarterly']
  },
  {
    id: 'DOC-004',
    name: 'Preventive Maintenance Procedures',
    description: 'Standard operating procedures for preventive maintenance tasks',
    category: 'Preventive Maintenance',
    fileType: 'docx',
    fileSize: 524288,
    relatedTo: null,
    relatedType: null,
    uploadedBy: 'Sarah Johnson',
    uploadedDate: '2024-01-10T09:00:00Z',
    expiryDate: null,
    tags: ['procedure', 'preventive', 'maintenance', 'sop']
  },
  {
    id: 'DOC-005',
    name: 'Conveyor Belt Inspection Photos',
    description: 'Photos from recent conveyor belt inspection showing belt condition',
    category: 'Daily records',
    fileType: 'jpg',
    fileSize: 3145728,
    relatedTo: 'WO-003',
    relatedType: 'workorder',
    uploadedBy: 'John Smith',
    uploadedDate: '2025-01-14T15:45:00Z',
    expiryDate: null,
    tags: ['inspection', 'photo', 'conveyor']
  },
  {
    id: 'DOC-006',
    name: 'Air Compressor Warranty Document',
    description: 'Warranty documentation for Atlas Copco GA 37 air compressor',
    category: 'License & Certification',
    fileType: 'pdf',
    fileSize: 1572864,
    relatedTo: 'ASSET-008',
    relatedType: 'asset',
    uploadedBy: 'Sarah Johnson',
    uploadedDate: '2018-10-15T11:00:00Z',
    expiryDate: '2023-10-15T23:59:59Z',
    tags: ['warranty', 'compressor', 'atlas copco']
  },
  {
    id: 'DOC-007',
    name: 'Emergency Response Procedures',
    description: 'Emergency shutdown and response procedures for all critical equipment',
    category: 'RCA',
    fileType: 'pdf',
    fileSize: 786432,
    relatedTo: null,
    relatedType: null,
    uploadedBy: 'Sarah Johnson',
    uploadedDate: '2024-06-15T10:00:00Z',
    expiryDate: null,
    tags: ['emergency', 'procedure', 'safety']
  },
  {
    id: 'DOC-008',
    name: 'Maintenance Cost Analysis 2024',
    description: 'Annual maintenance cost analysis and budget report',
    category: 'Quotation',
    fileType: 'xlsx',
    fileSize: 1310720,
    relatedTo: null,
    relatedType: null,
    uploadedBy: 'Sarah Johnson',
    uploadedDate: '2025-01-05T13:00:00Z',
    expiryDate: null,
    tags: ['report', 'cost', 'budget', 'analysis']
  },
  {
    id: 'DOC-009',
    name: 'Emergency Pump Failure Report',
    description: 'Detailed breakdown report of water pump failure and repair actions',
    category: 'Brakedown Report',
    fileType: 'pdf',
    fileSize: 2097152,
    relatedTo: 'WO-002',
    relatedType: 'workorder',
    uploadedBy: 'Mike Chen',
    uploadedDate: '2025-01-19T16:30:00Z',
    expiryDate: null,
    tags: ['failure', 'pump', 'repair', 'breakdown']
  }
];

export const analytics = {
  workOrderStats: {
    total: 156,
    open: 42,
    inProgress: 18,
    completed: 89,
    overdue: 7
  },
  thisMonth: {
    completedWOs: 24,
    totalCost: 18450,
    avgCompletionTime: 3.2,
    preventiveVsCorrective: { preventive: 65, corrective: 35 }
  },
  assetHealth: {
    operational: 85,
    maintenance: 8,
    degraded: 5,
    offline: 2
  },
  costTrends: [
    { month: 'Jul', cost: 12500 },
    { month: 'Aug', cost: 14200 },
    { month: 'Sep', cost: 13800 },
    { month: 'Oct', cost: 15600 },
    { month: 'Nov', cost: 16200 },
    { month: 'Dec', cost: 17800 },
    { month: 'Jan', cost: 18450 }
  ],
  downtimeByAsset: [
    { asset: 'Water Pump P-101', hours: 48 },
    { asset: 'Air Compressor AC-2', hours: 18 },
    { asset: 'HVAC Unit A1', hours: 12 },
    { asset: 'Conveyor Belt CB-1', hours: 6 }
  ]
};
